"use client";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { useState, useEffect } from "react";
import { UserLocationContext } from "/context/UserLocationContext";
import Provider from "./Provider";
const inter = Inter({ subsets: ["latin"] });

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export default function RootLayout({ children }) {
  const [userLocation, setUserLocation] = useState([]);

  const getUserLocation = () => {
    navigator.geolocation.getCurrentPosition(function (pos) {
      //console.log(pos);
      setUserLocation({
        lat: pos.coords.latitude,
        lng: pos.coords.longitude,
      });
    });
  };

  useEffect(() => {
    getUserLocation();
  }, []);
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Provider>
          <UserLocationContext.Provider
            value={{ userLocation, setUserLocation }}
          >
            <Navbar />
            {children}
          </UserLocationContext.Provider>
        </Provider>
      </body>
    </html>
  );
}
